MentorMentee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('base.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import SetPasswordForm

urlpatterns = [
    path("", views.Home.as_view(), name='home'),
    path("register/", views.Register.as_view(), name='register'),
    path("login/", views.Login.as_view(), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name='logout'),
    path("mentee_update/<pk>", views.MenteeUpdate.as_view(), name='mentee_update'),
    path("password_reset/", auth_views.PasswordResetView.as_view(
        template_name='auth/password_reset.html'), name='password_reset'
    ),
    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(
        template_name='auth/password_reset_done.html'), name='password_reset_done'
    ),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
        template_name='auth/password_reset_confirm.html', form_class=SetPasswordForm
        ), name='password_reset_confirm'
    ),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(
        template_name='auth/password_reset_complete.html'), name='password_reset_complete'
    ),
    path("mentor_search", views.MentorSearch.as_view(), name='mentor_search'),
    path("mentor_detail/<slug>", views.MentorDetail.as_view(), name='mentor_detail'),
    path("mentor_update/<pk>", views.MentorUpdate.as_view(), name='mentor_update'),
    path("chat/<chat_room>", views.ChatList.as_view(), name='chat'),
    path("chat_room_list/", views.ChatRoomList.as_view(), name='chat_room_list'),
]

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    TYPES = {
        'mentor': 'Mentor',
        'mentee': 'Mentee',
    }
    type = models.CharField(max_length=25, choices=TYPES, default='mentee')

    def unread_chat_count(self):
        return self.recieved_chats.filter(is_read=False).count()

class Mentor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='images')
    email = models.EmailField(max_length=254)
    job_title = models.CharField(max_length=50, blank=True)
    price = models.IntegerField(null=True, blank=True)
    category = models.CharField(max_length=50, blank=True)
    skill = models.CharField(max_length=50, blank=True)
    description = models.TextField(blank=True)
    approved = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-created']
    
    def __str__(self):
        return self.name.title()
    
class ChatRoom(models.Model):
    name = models.CharField(max_length=50, unique=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.name
    
    def last_chat(self):
        return self.chat_set.last()
    
    def unread_chat_count(self):
        return self.chat_set.filter(is_read=False).count()

class Chat(models.Model):
    sender = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, related_name='sent_chats'
    )
    reciever = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, related_name='recieved_chats'
    )
    room = models.ForeignKey(ChatRoom, on_delete=models.CASCADE) 
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return self.message

base/forms.py
from django.contrib.auth import forms as auth_forms
from .models import User, Mentor
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit
from crispy_bootstrap5.bootstrap5 import FloatingField

class UserCreationForm(auth_forms.UserCreationForm):
    first_name = forms.CharField(required=True, label='Name')
    email = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'email', 'type']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        field_divs = []
        for field_name, field in self.fields.items(): 
            field.help_text = None
            field_divs.append(Div(FloatingField(field_name), css_class='col-md-6')) 
        self.helper.layout = Layout(
            Div(*field_divs, css_class='row'), 
            Submit('submit', 'Register', css_class='btn btn-primary w-100')
        )

class LoginForm(auth_forms.AuthenticationForm):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        field_divs = []
        for field_name in self.fields.keys(): 
            field_divs.append(Div(FloatingField(field_name), css_class='col-md-12')) 
        self.helper.layout = Layout(
            Div(*field_divs, css_class='row'), 
            Submit('submit', 'Login', css_class='btn btn-primary w-100 mb-2')
        )

class MenteeForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ['first_name', 'email']
        labels = {'first_name' : 'Name'}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        field_divs = []
        for field_name in self.fields.keys(): 
            field_divs.append(Div(FloatingField(field_name), css_class='col-md-12')) 
        self.helper.layout = Layout(
            Div(*field_divs, css_class='row'), 
            Submit('submit', 'Submit', css_class='btn btn-primary w-100 mb-2')
        )

class SetPasswordForm(auth_forms.SetPasswordForm):
    class Meta:
        fields = ['new_password1', 'new_password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values(): field.help_text = None

class MentorForm(forms.ModelForm):
    class Meta:
        model = Mentor
        fields = ['name', 'email', 'job_title', 'price', 
                  'category', 'skill', 'image', 'description']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        field_divs = []
        for field_name in self.fields.keys():
            if field_name in ['image', 'description']:
                field_divs.append(Div(
                    field_name, css_class='col-md-12')
                ) 
            else:
                field_divs.append(Div(FloatingField(field_name), css_class='col-md-6')) 
        self.helper.layout = Layout(Div(
            *field_divs, css_class='row'), 
            Submit('submit', 'Submit', css_class='btn btn-primary w-100')
        )

base/views.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from .forms import UserCreationForm, LoginForm
from django.urls import reverse_lazy
from .models import User, Mentor, ChatRoom
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import LoginView
from .forms import MenteeForm, MentorForm
from django.db.models import Q, Max
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone

# Create your views here.
class Home(ListView):
    model = Mentor
    template_name = "base/home.html"
    queryset = Mentor.objects.filter(approved=True)[:4]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["year"] = timezone.now().year 
        return context
    
class Register(SuccessMessageMixin, CreateView):
    form_class = UserCreationForm
    template_name = 'auth/register.html'
    success_url = reverse_lazy('login')
    success_message = "Account created successfully."

class Login(SuccessMessageMixin, LoginView):
    form_class = LoginForm
    success_message = 'You are now logged in.'
    template_name = 'auth/login.html'
    
    def get_success_url(self):
        if self.request.user.type == 'mentee': 
            return reverse_lazy('home')
        slug = self.request.user.mentor.slug
        return reverse_lazy('mentor_detail', args=[slug])

class MenteeUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    form_class = MenteeForm
    template_name = 'base/mentee_form.html'
    success_message = "Profile updated successfully."

    def get_success_url(self):
        return reverse_lazy('home')
    
class MentorSearch(ListView):
    paginate_by = 16
    queryset = Mentor.objects.filter(approved=True)
    def get_queryset(self):
        query = self.request.GET.get('query')
        if query:
            return self.queryset.filter(
                Q(name__icontains=query) | Q(description__icontains=query) | 
                Q(job_title__icontains=query) | Q(category__icontains=query) | 
                Q(skill__icontains=query)
            )
        return self.queryset

class MentorDetail(DetailView):
    model = Mentor

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        chat_room = f'{self.object.user.username}-{self.request.user.username}'
        context["chat_room"] = chat_room 
        return context
    
class MentorUpdate(LoginRequiredMixin,SuccessMessageMixin, UpdateView):
    model = Mentor
    form_class = MentorForm
    success_message = "Profile updated successfully."
    
    def get_success_url(self):
        slug = self.object.slug
        return reverse_lazy('mentor_detail', args=[slug])

class ChatList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    
    def get_queryset(self):
        chat_room, _ = ChatRoom.objects.get_or_create(name=self.kwargs['chat_room'])
        return chat_room.chat_set.all()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        sender_username = self.request.user.username
        mentor_username = self.kwargs['chat_room'].split('-')[0]
        mentee_username = self.kwargs['chat_room'].split('-')[1]
        context["chat_room"] = self.kwargs['chat_room']
        context["mentor_username"] = mentor_username
        context["sender_username"] = sender_username
        if sender_username == mentor_username:
            context["reciever_username"] = mentee_username
        else:
            context["reciever_username"] = mentor_username
        return context
    
    def get(self, request, *args, **kwargs):
        chats = self.get_queryset()
        chats.filter(is_read=False).exclude(sender=request.user).update(is_read=True)
        return super().get(request, *args, **kwargs)
    
class ChatRoomList(LoginRequiredMixin, ListView):
    paginate_by = 16
    queryset = ChatRoom.objects.annotate(last_chat_created=Max('chat__created')).order_by('-last_chat_created')

    def get_queryset(self):
        if self.request.user.type == 'mentor':
            username = self.request.user.username + '-'
        else:
            username = '-' + self.request.user.username
        return super().get_queryset().filter(name__contains=username).filter(chat__isnull=False).distinct()

base/templates/base/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Mentor Mentee</title>
  <link rel="stylesheet" href="{% static "bootstrap.min.css" %}">
  <style>.asteriskField {display: none;}</style>
</head>

<body class='bg-primary-subtle'>
  <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand mx-md-5 ps-md-5" href="{% url "home" %}">MM</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
        aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor01">
        {% if user.is_authenticated %}
        {% if user.type == 'mentor' %}
        <ul class="navbar-nav me-auto">
          <li class="nav-item me-2">
            {% if 'mentor_detail' in request.path %}
              <a class="nav-link active" href="{% url "mentor_detail" user.mentor.slug %}">Hey {{user.get_full_name|title|truncatechars:20}}
                <span class="visually-hidden">(current)</span>
              </a>
            {% else %}
              <a class="nav-link" href="{% url "mentor_detail" user.mentor.slug %}">Hey {{user.get_full_name|title|truncatechars:20}}</a>
            {% endif %}
          </li>
          <li class="nav-item">
            {% if 'chat_room_list' in request.path %}
            <a class="nav-link active" href="{% url 'chat_room_list' %}">Messages 
              {% if user.unread_chat_count > 0 %} 
                <span class="badge rounded-pill bg-secondary">{{user.unread_chat_count}}</span> 
              {% endif %}
              <span class="visually-hidden">(current)</span>
            </a>
            {% else %}
            <a class="nav-link" href="{% url 'chat_room_list' %}">Messages 
              {% if user.unread_chat_count > 0 %} 
                <span class="badge rounded-pill bg-secondary">{{user.unread_chat_count}}</span>
              {% endif %}
            </a>
            {% endif %}
          </li>
          <li class="nav-item">
            <form method="post" action="{% url 'logout' %}">{% csrf_token %}
              <button class='btn btn-success btn-sm my-1 ms-md-3' type="submit">Log Out</button>
            </form>
          </li>
        </ul>
        {% else %}
        <ul class="navbar-nav me-auto">
          <li class="nav-item me-2">
            {% if 'mentee_update' in request.path %}
              <a class="nav-link active" href="{% url "mentee_update" user.pk %}">Hey {{user.get_full_name|title|truncatechars:20}}</a>
            {% else %}
              <a class="nav-link" href="{% url "mentee_update" user.pk %}">Hey {{user.get_full_name|title|truncatechars:20}}</a>
            {% endif %}
          </li>
          <li class="nav-item">
            {% if 'chat_room_list' in request.path %}
            <a class="nav-link active" href="{% url 'chat_room_list' %}">Messages 
              {% if user.unread_chat_count > 0 %} 
                <span class="badge rounded-pill bg-secondary">{{user.unread_chat_count}}</span>
              {% endif %}
              <span class="visually-hidden">(current)</span>
            </a>
            {% else %}
            <a class="nav-link" href="{% url 'chat_room_list' %}">Messages 
              {% if user.unread_chat_count > 0 %} 
                <span class="badge rounded-pill bg-secondary">{{user.unread_chat_count}}</span>
              {% endif %}
            </a>
            {% endif %}
          </li>
          <li class="nav-item">
            <form method="post" action="{% url 'logout' %}">{% csrf_token %}
              <button class='btn btn-success btn-sm my-1 ms-md-3' type="submit">Log Out</button>
            </form>
          </li>
        </ul>
        {% endif %}
        {% else %}
        <ul class="navbar-nav me-auto mx-5">
          <li class="nav-item me-2">
            {% if 'register' in request.path %}
            <a class="nav-link active" href="{% url "register" %}">Register
              <span class="visually-hidden">(current)</span>
            </a>
            {% else %}
            <a class="nav-link" href="{% url "register" %}">Register</a>
            {% endif %}

          </li>
          <li class="nav-item">
            {% if 'login' in request.path %}
            <a class="nav-link active" href="{% url "login" %}">Login
              <span class="visually-hidden">(current)</span>
            </a>
            {% else %}
            <a class="nav-link" href="{% url "login" %}">Login</a>
            {% endif %}
          </li>
        </ul>
        {% endif %}
        <form class="d-flex me-md-5 px-md-5" action={% url "mentor_search" %}>
          <input class="form-control me-sm-2" type="search" placeholder="Search" name='query'>
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  {% if messages %}
      {% for message in messages %}
        <div class="alert alert-info text-center" role='alert'>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle me-2" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
            <path d="m10.97 4.97-.02.022-3.473 4.425-2.093-2.094a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05"/>
          </svg>
          {{message}}
        </div>

      {% endfor %}

  {% endif %}
  <div class='bg-primary'>
    {% block hero %}{% endblock hero %}
  </div>
  <div class='container'>
    {% block content %}{% endblock content %}
  </div>
</body>
<script src="{% static "bootstrap.bundle.min.js" %}"></script>
<script>
  const alert = document.querySelector('.alert');
  if (alert) {
    setTimeout(() => {
      alert.style.transition = 'opacity 1s';
      alert.style.opacity = '0';
      setTimeout(() => {alert.remove();}, 1000);
    }, 4000);
  }
</script>
</html>

base/templates/base/chat_list.html
{% extends "base/base.html" %}
{% load humanize %}

{% block content %}
<div class="row my-5 justify-content-center">
  <div class="col-md-99 col-lg-10 col-xl-11">
      <ul class="list-unstyled" id="messages">
        {% for chat in object_list %}
          {% if chat.sender.username == mentor_username %}
            <li class="d-flex justify-content-end mb-4">
              <div class='col-md-6'>
                <div class="card bg-warning-subtle">
                  <div class="card-header d-flex justify-content-between p-3">
                    <p class="fw-bold mb-0">{{chat.sender.get_full_name|title|truncatechars:20}}</p>
                    <p class="text-muted small mb-0 ms-5"><i class="far fa-clock"></i>{{chat.created|naturaltime}}</p>
                  </div>
                  <div class="card-body">
                    <p class="mb-0">
                      {{chat.message}}
                    </p>
                  </div>
                </div>
              </div>
            </li>
          {% else %}
            <li class="d-flex mb-4">
              <div class='col-md-6'>
                <div class="card bg-info-subtle">
                  <div class="card-header d-flex justify-content-between p-3">
                    <p class="fw-bold mb-0">{{chat.sender.get_full_name|title|truncatechars:20}}</p>
                    <p class="text-muted small mb-0 ms-5"><i class="far fa-clock"></i>{{chat.created|naturaltime}}</p>
                  </div>
                  <div class="card-body">
                    <p class="mb-0">
                      {{chat.message}}
                    </p>
                  </div>
                </div>
              </div>
            </li>
          {% endif %}
        {% endfor %}
      </ul>
      <div class="form-outline mb-3">
        <textarea class="form-control" id="text-area" rows="4"></textarea>
      </div>
      <button type="button" class="btn btn-success float-end px-5" id="send">Send</button>

  </div>

</div>
{{ chat_room|json_script:"chat-room" }}
{{ sender_username|json_script:"sender-username" }}
{{ reciever_username|json_script:"reciever-username" }}
<script>
  window.scrollTo(0, document.body.scrollHeight)
  const chatRoom = JSON.parse(document.getElementById('chat-room').textContent)
  const senderUsername = JSON.parse(document.getElementById('sender-username').textContent)
  const recieverUsername = JSON.parse(document.getElementById('reciever-username').textContent)
  const truncateChars = (str, num) => {
    if (str.length <= num) {
        return str
    }
    return `${str.slice(0, num)}...`
  }
  const url = `ws://${window.location.host}/ws/chat/${chatRoom}`
  const chatWebSocket = new WebSocket(url)
  chatWebSocket.onmessage = (event) => {
      const data = JSON.parse(event.data)
      const messages = document.querySelector('#messages')
      mentorUsername = chatRoom.split('-')[0]
      if (data.senderUsername === mentorUsername) {
        messages.insertAdjacentHTML('beforeend', 
          `<li class="d-flex justify-content-end mb-4">
            <div class='col-md-6'>
              <div class="card bg-warning-subtle">
                <div class="card-header d-flex justify-content-between p-3">
                  <p class="fw-bold mb-0">${truncateChars(data.fullName, 20)}</p>
                  <p class="text-muted small mb-0 ms-5"><i class="far fa-clock"></i>${data.created}</p>
                </div>
                <div class="card-body">
                  <p class="mb-0">
                    ${data.chat}
                  </p>
                </div>
              </div>
            </div>
          </li>`
        )
      } else {
        messages.insertAdjacentHTML('beforeend', 
          `<li class="d-flex mb-4">
            <div class='col-md-6'>
              <div class="card bg-info-subtle">
                <div class="card-header d-flex justify-content-between p-3">
                  <p class="fw-bold mb-0">${truncateChars(data.fullName, 20)}</p>
                  <p class="text-muted small mb-0 ms-5">${data.created}</p>
                </div>
                <div class="card-body">
                  <p class="mb-0">
                    ${data.chat}
                  </p>
                </div>
              </div>
            </div>
          </li>`
        )
      }
  }

  const sendButton = document.querySelector('#send')
  const textArea = document.querySelector('#text-area')

  sendButton.addEventListener('click', () => {
    const chat = textArea.value
    if (chat) {
      chatWebSocket.send(JSON.stringify({ 
        senderUsername: senderUsername,
        recieverUsername: recieverUsername,
        chatRoom: chatRoom,
        chat: chat
      }))
      textArea.value = ''
    }
  })
</script>
{% endblock content %}

base/templates/base/chatroom_list.html
{% extends "base/base.html" %}
{% load humanize %}

{% block content %}
<div class="row justify-content-center my-5">
    <div class="col-md-12 col-lg-11 col-xl-10 mb-4 mb-md-0">
        {% for chat_room in object_list %}
            <div class="card mb-2">
                <div class="card-body">
                    <ul class="list-unstyled mb-0">
                        <li>
                            <a href="{% url "chat" chat_room %}" class="text-decoration-none">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="d-flex align-items-center">
                                        {% if chat_room.last_chat.sender == request.user %}
                                            <p class="fw-bold mb-0 me-3">{{ chat_room.last_chat.reciever.first_name|title|truncatechars:20 }}</p>
                                        {% else %}
                                            <p class="fw-bold mb-0 me-3">{{ chat_room.last_chat.sender.first_name|title|truncatechars:20 }}</p>
                                        {% endif %}
                                        {% if chat_room.unread_chat_count and request.user != chat_room.last_chat.sender %}
                                            <p class="small fw-bold text-black-50 mb-0 me-3">{{ chat_room.last_chat|truncatechars:80 }}</p>
                                        {% else %}
                                            <p class="small text-muted mb-0 me-3">{{ chat_room.last_chat|truncatechars:80 }}</p>
                                        {% endif %}
                                    </div>
                                    <div class="d-flex align-items-center">
                                        <p class="small text-muted
                                         mb-0 me-2">{{ chat_room.last_chat.created|naturaltime }}</p>
                                        {% if chat_room.unread_chat_count and request.user != chat_room.last_chat.sender %}
                                            <span class="badge rounded-pill bg-secondary">{{chat_room.unread_chat_count}}</span>
                                        {% endif %}
                                    </div>
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        {% empty %}
            <h3 class='mb-5 mt-4 fw-normal'>No Messages found.</h3>
        {% endfor %}
    </div>
</div>
{% endblock content %}

base/templates/base/home.html
{% extends "base/base.html" %}

{% block hero %}
<div class="pt-5 pb-5 mb-5 text-center">
  <!-- <img class="d-block mx-auto mb-4" src="../assets/brand/bootstrap-logo.svg" alt="" width="72" height="57"> -->
  <h1 class="display-4 text-white pt-2 mb-4">MentorMentee</h1>
  <div class="col-lg-6 mx-auto px-5 pb-2">
    <p class="text-light lead">Something short and leading about the collection below—its contents, the creator, etc. Make
      it short and sweet, but not too short.</p>
  </div>
</div>
{% endblock hero %}

{% block content %}
<div class="row my-5">
  {% for mentor in mentor_list %}
  <div class="col-lg-3">
    <a class='nav-link' href="{% url "mentor_detail" mentor.slug %}">
      <div class="card mb-4 bg-light">
        <div class="card-body text-center">
          {% if mentor.image %}<img src="{{mentor.image.url}}" alt="avatar" class="rounded-circle img-fluid"
            style="width: 150px;">
          {% endif %}
          <h5 class="mt-3 mb-2">{{mentor.name|title}}</h5>
          <p class="text-muted mb-1">{{mentor.job_title|title}}</p>
          <p class="text-muted mb-1">Price: ${{mentor.price}}</p>
        </div>
      </div>
    </a>
  </div>

  {% empty %}
    <h3 class='mb-5 mt-4 fw-normal'>No Mentors found.</h3>
  {% endfor %}

</div>
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top border-dark-subtle">
  <div class="col-md-4 d-flex align-items-center">
    <!-- <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
      <svg class="bi" width="30" height="24">
        <use xlink:href="#" />
      </svg>
    </a> -->
    <span class="mb-3 mb-md-0 text-body-secondary">&copy; {{year}} Company, Inc</span>
  </div>
  <span>Made with 
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart-fill text-danger" viewBox="0 0 16 16">
      <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1" />
    </svg> by <a class='text-decoration-none text-info fw-semibold' href='https://www.fiverr.com/yuvraj_webdev2'>Yuvraj Rana</a>
  </span>
  <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
    <li class="ms-3"><a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
      class="bi bi-twitter-x text-black-50" viewBox="0 0 16 16"><path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z" /></svg></a>
    </li>
    <li class="ms-3"><a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-linkedin text-black-50" viewBox="0 0 16 16">
      <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z" /></svg></a>
    </li>
  </ul>
</footer>
{% endblock content %}

base/templates/base/mentee_form.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row justify-content-center my-5">
  <div class="col-md-6">
    <h3 class="fw-normal mb-3">Profile</h3>
    {% crispy form %}
  </div>
</div>
{% endblock content %}